In [1]:
import pandas as pd

In [2]:
funcionarios = {
    "Nome": ["Douglas Ribeiro", "Eduardo Brilhante", "Caio Santos"],
    "CPF": ["123.456.789-00", "987.654.321-00", "456.789.123-00"],
    "Status": ["Regular", "Pendente", "Regular"]
}

In [3]:
df = pd.DataFrame(funcionarios)

In [4]:
# Filtra apenas os funcionários com pendência
pendencias = df[df["Status"] == "Pendente"]

# Salva o relatório em Excel
pendencias.to_excel("relatorio_pendencias.xlsx", index=False)

In [5]:
print("=======================")
print("Relatório de Pendências")
print("=======================")

=======================
Relatório de Pendências
=======================

In [6]:
print("\nDataFrame completo:")
display(df)

DataFrame completo:

                Nome             CPF    Status
0    Douglas Ribeiro  123.456.789-00   Regular
1  Eduardo Brilhante  987.654.321-00  Pendente
2        Caio Santos  456.789.123-00   Regular

In [7]:
print("\nFuncionários com pendências")
display(pendencias)

Funcionários com pendências

                Nome             CPF    Status
1  Eduardo Brilhante  987.654.321-00  Pendente

In [8]:
print("\nArquivo 'relatorio_pendencias.xlsx' criado com sucesso!")

Arquivo 'relatorio_pendencias.xlsx' criado com sucesso!